### ISSUE TITLE
Worker and panel not working

### ISSUE THREAD

**Issue by MrCoala** [ccarney16/pterodactyl-containers#102]
An automatic update broke the panel and the worker

Log of pterodactyl_worker_1:

Pre-start: Waiting for database connection...

```
In Application.php line 690:

  Class 'Appstract\BladeDirectives\BladeDirectivesServiceProvider' not found


Pre-start: Waiting for database connection...

In Application.php line 690:

  Class 'Appstract\BladeDirectives\BladeDirectivesServiceProvider' not found
```

.. repeats itself. Database is up and running without any issues

The pterodactyl_panel_1 throws this:

```
Starting Pterodactyl Panel v1.3.1...
2021/03/18 21:02:58 [error] 55#55: *10 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to "Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer::__construct()" must be a boolean or a callable, "string" given. in /var/www/html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:53
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(538): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->__construct()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(492): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(475): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(454): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse()
#4 /var/www/html/vendor/laravel/framew...PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to "Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer::__construct()" must be a boolean or a callable, "string" given. in /var/www/html/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:53
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(538): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->__construct()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(492): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(475): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(454): Illuminate\Foundation\Exceptions\Handler->convertExceptionToRespo
src:"XXX.XXX.XXX.XXX" time:"18/Mar/2021:21:02:58 +0000" req:"GET / HTTP/1.1" status:"500" agent:"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/x.x.x.x Safari/537.36" for:"-"
```

Any idea on how i could solve that?

- i flushed the logs
- checked the database connection
- moved the docker-compose folder/file to another machine and tried to run there with the same result

**Comment by LDShadowLord** [comment]
I'm having a similar issue with the
```
In Application.php line 690:

  Class 'Appstract\BladeDirectives\BladeDirectivesServiceProvider' not found
```
error. The only fix i've found thus far is rolling back to 1.2.2 which runs happily.

**Comment by ccarney16** [comment]
purge data/cache within the project directory, its unknown as to why pterodactyl is not purging this directory automatically.

**Comment by ccarney16** [comment]
From v1.3.2, the image no longer stores its bootstrap cache within /data.
