### ISSUE TITLE
How to modify networking pool for Wings daemon?

### ISSUE THREAD

**Issue by dennorske** [ccarney16/pterodactyl-containers#51]
Hello!

Great effort making this dockerized, and after some tweaking and fiddling around, I have managed to (almost) get it fully up.
Wings don't want to start. Most likely, this is caused by the machine being a client connected to a OpenVPN server, and the pools are used to forward traffic through this.
I do believe by manually configuring a pool, I can be able to overcome this problem.
Here is my error:

```
daemon_1  | 
daemon_1  | > pteronode@0.6.13 start /srv/daemon
daemon_1  | > node src/index.js | node_modules/bunyan/bin/bunyan -o short
daemon_1  | 
daemon_1  | 08:20:12.306Z  INFO wings: + ------------------------------------ +
daemon_1  | 08:20:12.307Z  INFO wings: | Running Pterodactyl Daemon v0.6.13    |
daemon_1  | 08:20:12.307Z  INFO wings: |        https://pterodactyl.io        |
daemon_1  | 08:20:12.307Z  INFO wings: |                                      |
daemon_1  | 08:20:12.307Z  INFO wings: |  Copyright 2015 - 2020 Dane Everitt  |
daemon_1  | 08:20:12.307Z  INFO wings: |           and contributors           |
daemon_1  | 08:20:12.307Z  INFO wings: + ------------------------------------ +
daemon_1  | 08:20:12.307Z  INFO wings: Loading modules, this could take a few seconds.
daemon_1  | 08:20:12.513Z  INFO wings: Modules loaded, starting Pterodactyl Daemon...
daemon_1  | 08:20:12.563Z  INFO wings: Configuring user pterodactyl (id: 500) as the owner of all server files.
daemon_1  | 08:20:12.565Z  INFO wings: Configuring timezone file location...
daemon_1  | 08:20:12.565Z  INFO wings: Checking container networking environment...
daemon_1  | 08:20:12.569Z  WARN wings: No isolated network interface for containers was detected, creating one now.
daemon_1  | 08:20:12.572Z FATAL wings: A fatal error caused the daemon to abort the startup.
daemon_1  |     Error: (HTTP code 403) unexpected - Pool overlaps with other one on this address space 
daemon_1  |         at /srv/daemon/node_modules/docker-modem/lib/modem.js:257:17
daemon_1  |         at getCause (/srv/daemon/node_modules/docker-modem/lib/modem.js:287:7)
daemon_1  |         at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:256:5)
daemon_1  |         at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:232:14)
daemon_1  |         at emitNone (events.js:111:20)
daemon_1  |         at IncomingMessage.emit (events.js:208:7)
daemon_1  |         at endReadableNT (_stream_readable.js:1064:12)
daemon_1  |         at _combinedTickCallback (internal/process/next_tick.js:139:11)
daemon_1  |         at process._tickDomainCallback (internal/process/next_tick.js:219:9)
daemon_1  |     --
daemon_1  |     additional: {
daemon_1  |       "statusCode": 403,
daemon_1  |       "json": {
daemon_1  |         "message": "Pool overlaps with other one on this address space"
daemon_1  |       }
daemon_1  |     }
daemon_1  | 08:20:12.572Z ERROR wings: You should forcibly quit this process (CTRL+C) and attempt to fix the issue.
```

Also, I would believe that Wings would also attach itself to the network created by docker-compose on "up". (ref: `No isolated network interface for containers was detected, creating one now.`)
I did try to create a new network and manually define this under all the services, but it didn't change the error from Wings.
Do you have any insight on how this can be manually defined with wings?

**Comment by nrgbistro** [comment]
I am having the same issue. How exactly do you manually configure the network/pool?

**Comment by dennorske** [comment]
I tried setting the docker-compose setup on another machine, and it worked well. I have a theory that the pool being set up for the daemon is in a static range, and it doesn't adapt to existing pools.

**Comment by Magi1053** [comment]
Wings only works on the v1.0.0-beta version of Panel, the version this image uses is the stable v0.7.17. Panel 1.0 is not production ready, but will probably be added to this image soon enough.

**Comment by dennorske** [comment]
I had the daemon working on a different machine though. What do you mean exactly?

**Comment by ccarney16** [comment]
You can create the network manually by running this command: `docker network create pterodactyl_nw`. The daemon will see the new network and adapt accordingly.

**Comment by ccarney16** [comment]
Closing: inactivity and older version of the panel
