### ISSUE TITLE
Fix permisson to resolve 500 error

### ISSUE THREAD

**Issue by Syntax3rror404** [ccarney16/pterodactyl-containers#96]
After migration to a new system and updating from 0.7 i get 500 errors on some pages. For example after logout. Is there a script inside the container to fix this after executing? Or do you know what are the correct folder an file permissions?

**Comment by ccarney16** [comment]
Can you check your current logs? laravel logs are in ./data/storage/logs.

**Comment by Syntax3rror404** [comment]
Hi @ccarney16 :) oh yes, thank you for your time

access.error.log
```
[...]
2021/01/04 16:16:26 [error] 25#25: *2088 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ReflectionException: Class db.connection does not exist in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:779
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(779): ReflectionClass->__construct('db.connection')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(658): Illuminate\Container\Container->build('db.connection')
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(609): Illuminate\Container\Container->resolve('db.connection', Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(735): Illuminate\Container\Container->make('db.connection', Array)
#4 /var/www/html/app/Exceptions/Handler.php(142): Illuminate\Foundation\Application->make('db.connection')
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(112): Pterodactyl\Exceptions\Handle...PHP message: PHP Fatal error:  Uncaught ReflectionException: Class db.connection does not exist in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:779
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(779): ReflectionClass->__construct('db.connection')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(658): Illuminate\Container\Container->build('db.connection')
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(609): Illuminate\Container\Container->resolve('db.connection', Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(735): Illuminate\Container\Container->make('db.connection', Array)
#4 /var/www/html/app/Exceptions/Handler.php(142): Illuminate\Foundation\Application->make('db.connection')
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExce
2021/01/04 16:16:29 [error] 25#25: *2090 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ReflectionException: Class db.connection does not exist in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:779
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(779): ReflectionClass->__construct('db.connection')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(658): Illuminate\Container\Container->build('db.connection')
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(609): Illuminate\Container\Container->resolve('db.connection', Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(735): Illuminate\Container\Container->make('db.connection', Array)
#4 /var/www/html/app/Exceptions/Handler.php(142): Illuminate\Foundation\Application->make('db.connection')
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(112): Pterodactyl\Exceptions\Handle...PHP message: PHP Fatal error:  Uncaught ReflectionException: Class db.connection does not exist in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:779
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(779): ReflectionClass->__construct('db.connection')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(658): Illuminate\Container\Container->build('db.connection')
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(609): Illuminate\Container\Container->resolve('db.connection', Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(735): Illuminate\Container\Container->make('db.connection', Array)
#4 /var/www/html/app/Exceptions/Handler.php(142): Illuminate\Foundation\Application->make('db.connection')
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExce
2021/01/05 10:32:20 [error] 55#55: *570 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ErrorException: file_put_contents(/data/storage/framework/views/5ec98f73456acbfa9ca695d9d04acd7c7a76afc9.php): failed to open stream: No space left on device in /var/www/
```

What? No space left on device?
``` 
[root@dockersrv1 logs]# df -h
Filesystem                          Size  Used Avail Use% Mounted on
devtmpfs                             13G     0   13G   0% /dev
tmpfs                                13G     0   13G   0% /dev/shm
tmpfs                               4.9G  3.2M  4.9G   1% /run
tmpfs                               4.0M     0  4.0M   0% /sys/fs/cgroup
/dev/mapper/fedora_dockersrv1-root  174G   97G   77G  56% /
tmpfs                                13G  4.0K   13G   1% /tmp
/dev/mapper/fedora_dockersrv1-var    15G   11G  4.5G  71% /var
/dev/vda2                           495M  232M  264M  47% /boot
/dev/mapper/fedora_dockersrv1-home   10G  104M  9.9G   2% /home
/dev/vda1                           250M  8.5M  242M   4% /boot/efi
overlay                              15G   11G  4.5G  71% /var/lib/docker/overlay2/da45502c848bd57c6929913d9ad40173ca40fe13190546976386ca8a426f49b5/merged
overlay                              15G   11G  4.5G  71% /var/lib/docker/overlay2/473eab418e087228f6f42e95849e9b6ca3c028f9b3ec6ce13745068dfada87f9/merged
overlay                              15G   11G  4.5G  71% /var/lib/docker/overlay2/5a24297b5f8fe0b3c61d6f0e5e6334c177058ef75cf73f89f32ae750ea01ccb2/merged
overlay                              15G   11G  4.5G  71% /var/lib/docker/overlay2/5f5d1d29bddfe53740bf5282738fc46df0fd01419189ecbfd0566a53762081e3/merged
overlay                              15G   11G  4.5G  71% /var/lib/docker/overlay2/ebadeeddb9304d9ba35f3642049f0f387c69346999cf56acbf01bf49717dd66b/merged
overlay                              15G   11G  4.5G  71% /var/lib/docker/overlay2/dcad8ec02f77913d2df64c26d237c6042b79ea56a5bb8ba2a33c2353cccddc8b/merged
overlay                              15G   11G  4.5G  71% /var/lib/docker/overlay2/f779ef4f28cc87b5a0823df2438d15fea5898ad545e5531fa1bbd211b8f5e530/merged
overlay                              15G   11G  4.5G  71% /var/lib/docker/overlay2/25ce6533015a8cd72639221bf1f17037da61c946fb49d369978d9e1bae279497/merged
overlay                              15G   11G  4.5G  71% /var/lib/docker/overlay2/eb30848b2b2bd8c258cc27d13aeee988685cdd031cf55896cca06d3af6f086b5/merged
overlay                              15G   11G  4.5G  71% /var/lib/docker/overlay2/8fe8a3745062c082617f50081af4b5c067bb06c767203565072fd536a8d0f107/merged
overlay                              15G   11G  4.5G  71% /var/lib/docker/overlay2/3a2e42ba0ba27636cd577f2e1cc9ee4c060dfda2023573fe2d1f5d3425b461e5/merged
overlay                              15G   11G  4.5G  71% /var/lib/docker/overlay2/b8fa7770ffc5c1a189f8b3693cd82c0bc2060103731929adcd11aa8dfe18eb3e/merged
overlay                              15G   11G  4.5G  71% /var/lib/docker/overlay2/d3e1a4e59a8e825ec7c247755469cce0c13d4bb2dfd1ed514593e6657e2a8fb2/merged
overlay                              15G   11G  4.5G  71% /var/lib/docker/overlay2/2ddd64b9a0615409571602545b656048aadd1ab88b6461a0faad4a34eb3caf57/merged
overlay                              15G   11G  4.5G  71% /var/lib/docker/overlay2/dc0746c19036cfe1054e99f3cb917c4afe8c7b75a72b43cca0d90bbb602620aa/merged
overlay                              15G   11G  4.5G  71% /var/lib/docker/overlay2/78257131f88c9cf63d707034069c0af07a67499de2ba14d4dfb979f323e71527/merged
overlay                              15G   11G  4.5G  71% /var/lib/docker/overlay2/a60711a715aab1e4509ef7c5a2cae43dc8329426edbdc47d2d845205ead4b47d/merged
overlay                              15G   11G  4.5G  71% /var/lib/docker/overlay2/e9d09ddb6f9cb1c5777f381f3fa6310559e87ff34632034101bb56815c3b0c3b/merged
overlay                              15G   11G  4.5G  71% /var/lib/docker/overlay2/5637ac3d08ca7891e0b15b1979a76eedadfd28f6b24c0ea739832bb4d4226891/merged
overlay                              15G   11G  4.5G  71% /var/lib/docker/overlay2/24f17facbb7882d33494351599fb283bedb162b1a24758f9a2044863ffd45d23/merged
overlay                              15G   11G  4.5G  71% /var/lib/docker/overlay2/8883e739852b4d1278a499c987b8ac2d87fd7ca31c1a0c3551948fde2a7fc644/merged
overlay                              15G   11G  4.5G  71% /var/lib/docker/overlay2/a31924ef33cc2545a41a27c510fd5a07b27068fe85a2a3c8463e70fdea0b2ade/merged
overlay                              15G   11G  4.5G  71% /var/lib/docker/overlay2/e0a0ae3fc487066ea7a2498b2e326f18538f8e57b8ebf0da1de138bb7a55499e/merged
overlay                              15G   11G  4.5G  71% /var/lib/docker/overlay2/5baa348a55025b8d2ecdce5a00ffd6ca48e9335c54a9097d1e71c47452a7a950/merged
tmpfs                               2.5G     0  2.5G   0% /run/user/1000
overlay                              15G   11G  4.5G  71% /var/lib/docker/overlay2/3873a6afdd1a8d50fceee41016efc6f2bc7d16895031a8d290adc4ee4bb1551c/merged
overlay                              15G   11G  4.5G  71% /var/lib/docker/overlay2/fcf4999cda8157070a0b139ce8f843191d4cfce770ef9de0bf51ad07eb4fd569/merged
overlay                              15G   11G  4.5G  71% /var/lib/docker/overlay2/3039690851d708ab648c9181cbc37f21907f832e8bd89f0b318eb25b1b5b8b78/merged
```

**Comment by ccarney16** [comment]
Your /var and /home dont have a lot of space left, you should shrink your / partition and expand /var and /home.

**Comment by Syntax3rror404** [comment]
I've checked the db logs, but it works fine.

**Comment by ccarney16** [comment]
I just checked the date on the logs, and those are at the beginning of the month, mind checking what permissions your logs are set to? otherwise you can delete them and see what happens.
